<?php
require_once 'config/database.php';
require_once 'vendor/autoload.php'; // Changed from libs/intervention/vendor/autoload.php

use Intervention\Image\ImageManager;
use Intervention\Image\Drivers\Gd\Driver;
use Intervention\Image\Geometry\Point;
use Intervention\Image\Geometry\Rectangle;

// Inisialisasi Image Manager (v2.7.2 approach)
$manager = new ImageManager(['driver' => 'gd']);

// Ambil data dari form
$infografisId = $_POST['infografis_id'] ?? null;
if (!$infografisId) {
    throw new Exception('Infografis ID is required');
}

// Ambil data dari database
$infografis = getData('infografis', "id = $infografisId")[0] ?? null;
if (!$infografis) {
    throw new Exception('Infografis data not found');
}
$statistik = getData('statistik', "infografis_id = $infografisId");

// Buat gambar infografis (v2.7.2 syntax)
$image = $manager->canvas(800, 1200, '#ffffff');

// Tambahkan judul (updated text positioning for v2.7.2)
$image->text($infografis['judul'], 400, 50, function($font) {
    $fontPath = '/Users/windysabtami/Herd/infografis_1/fonts/Roboto-Bold.ttf';
    
    if (!file_exists($fontPath)) {
        throw new Exception("Font file missing: $fontPath");
    }
    
    $font->file($fontPath);  // Changed from filename() to file()
    $font->size(36);
    $font->color('#000000');
    $font->align('center');
    $font->valign('top');
});

// Apply the same validation to ALL other font usages
$fontChecks = function ($fontPath) {
    if (!file_exists($fontPath)) {
        throw new Exception("Font file missing: $fontPath");
    }
    if (!is_readable($fontPath)) {
        throw new Exception("Font not readable: $fontPath");
    }
    if (filesize($fontPath) < 150000) {
        throw new Exception("Invalid font file (corrupted/wrong format): $fontPath");
    }
};

// Tambahkan deskripsi
$image->text($infografis['deskripsi'], 400, 100, function ($font) use ($fontChecks) {
    $fontPath = '/Users/windysabtami/Herd/infografis_1/fonts/Roboto-Regular.ttf';
    $fontChecks($fontPath);

    $font->file($fontPath);  // Changed from filename() to file()
    $font->size(18);
    $font->color('#333333');
    $font->align('center');
    $font->valign('top');
});

// Define variables needed for the chart
// Tambahkan setelah mengambil data statistik
if (empty($statistik)) {
    throw new Exception('Tidak ada data statistik');
}

// Perbaiki perhitungan maxValue
$maxValue = max(array_column($statistik, 'nilai')) ?: 1; // Hindari division by zero
$startY = 500; // Tambahkan posisi Y awal
$barWidth = 80; // Tambahkan lebar bar
$colors = ['#FF5733', '#33FF57', '#3357FF']; // Pastikan warna cukup

// Tambahkan statistik (updated rectangle drawing)
foreach ($statistik as $index => $stat) {
    $barHeight = (int)round(($stat['nilai'] / $maxValue) * 400);
    $x = 150 + ($index * 120);
    
    // Draw rectangle (v2.7.2 syntax)
    $image->rectangle($x, $startY + 400 - $barHeight, $x + $barWidth, $startY + 400, function ($draw) use ($colors, $index) {
        $draw->background($colors[$index % count($colors)]);
    });

    // Tambahkan label
    $image->text($stat['label'], $x + ($barWidth / 2), $startY + 420, function ($font) {
        $fontPath = realpath(__DIR__ . '/fonts/Roboto-Regular.ttf');
        if (!$fontPath) {
            throw new Exception('Font file not found: ' . __DIR__ . '/fonts/Roboto-Regular.ttf');
        }
        $font->file($fontPath);  // Changed from filename() to file()
        $font->size(14);
        $font->color('#000000');
        $font->align('center');
    });

    // Tambahkan nilai
    // Di bagian nilai (masih menggunakan __DIR__)
    $image->text($stat['nilai'], $x + ($barWidth / 2), $startY + 380 - $barHeight, function ($font) {
        $font->file('/Users/windysabtami/Herd/infografis_1/fonts/Roboto-Bold.ttf');  // Changed from filename() to file()
        $font->size(16);
        $font->color('#000000');
        $font->align('center');
    });

    // Di footer
    $image->text('Generated by Infografis Generator', 400, 1150, function ($font) {
        $font->file('/Users/windysabtami/Herd/infografis_1/fonts/Roboto-Regular.ttf');  // Changed from filename() to file()
        $font->size(14);
        $font->color('#777777');
        $font->align('center');
    });
}

// Ensure outputs directory exists
if (!file_exists('outputs')) {
    mkdir('outputs', 0755, true);
}

// Simpan gambar
$filename = 'outputs/infografis_' . $infografisId . '_' . time() . '.png';
$image->save($filename);

// Tampilkan gambar
header('Content-Type: image/png');
readfile($filename);
exit;
